version: 2
jobs:
  build_and_test:
    working_directory: ~/mootube
    docker:
      - image: php:7.1
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      # Installation
      - run:
          name: Install System Packages
          command: apt-get update && apt-get -y install git unzip zlib1g-dev
      - run:
          name: Install PHP Extensions
          command: docker-php-ext-install pdo pdo_mysql zip
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
            php composer-setup.php && \
            php -r "unlink('composer-setup.php');" && \
            chmod +x ./composer.phar && \
            mv ./composer.phar /usr/local/bin/composer

      # Dependencies
      - checkout
      - restore_cache:
          key: mootube-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
      - run: composer install --prefer-dist --no-interaction
      # Force pulling Simple PHPUnit dependencies to be able to cache them as well
      - run: ./vendor/bin/simple-phpunit --version
      - save_cache:
          key: mootube-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
          paths:
            - '/root/.composer/cache'
            - './vendor'

      # Database
      - run: ./bin/console doctrine:database:create --env=test
      - run: ./bin/console doctrine:schema:create --env=test
      - run: ./bin/console hautelook_alice:doctrine:fixtures:load --no-interaction

      # To use server:start we need to install pcntl extension
      - run:
          name: Run web server in background
          command: ./bin/console server:run
          background: true

      # Testing
      - run: ./bin/console lint:yaml app/config
      - run: ./bin/console lint:twig app/Resources
      - run: ./vendor/bin/simple-phpunit

  deploy:
    working_directory: ~/mootube
    docker:
      - image: ansible/ansible:ubuntu1604
    steps:
      # Installation
      - run:
          name: Install System Packages
          command: pip install --upgrade pip && pip install ansible

      # Dependencies
      - checkout
      - restore_cache:
          key: mootube-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
      - run: ansible-galaxy install -r ansible/requirements.yml
      - save_cache:
          key: mootube-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
          paths:
            - '/root/.ansible/roles'

      # @TODO Deploy to AWS here...

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
