---
- hosts: aws

  vars_files:
    - ./vars/vars.yml

  vars_prompt:
    - name: git_branch
      prompt: 'Enter a branch to deploy'
      default: master
      private: no

  vars:
    # Ansistrano vars
    ansistrano_deploy_to: "{{ project_deploy_dir }}"
    ansistrano_deploy_via: git
    ansistrano_git_repo: git@github.com:weaverryan/ansistrano-testing-repo.git
    ansistrano_git_branch: "{{ git_branch }}"
    ansistrano_git_identity_key_path: "{{ playbook_dir }}/id_rsa"

    # Custom Ansistrano hooks
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"

  roles:
    - carlosbuenosvinos.ansistrano-deploy
